[package]
name = "rs-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.24.0", features = ["event-stream"] }
rand = "0.8.5"
rand_xorshift = "0.3.0"
